name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - scipy
  - palettable
  - bqplot
  - h5py
  - geopandas
  - contextily
  - webcolors
  - ipyleaflet
  - openpyxl
  - ipyvolume
